### ISSUE TITLE
LocalThickness accepts colour images

### ISSUE THREAD

**Issue by rimadoma** [fiji/LocalThickness#3]
Issue identified on [ImageJ forum](http://forum.imagej.net/t/need-help-with-bonej-plugin/3929/): if called via the menu entry _Local Thickness (masked, calibrated, silent)_, the plugin accepts 8-bit colour images even though it shouldn't according to the [documentation](http://www.optinav.info/LocalThicknessEd.pdf). Mea culpa.

**Comment by ctrueden** [comment]
Fixed by #4. Thanks @rimadoma!
