### ISSUE TITLE
Spacing info

### ISSUE THREAD

**Issue by soupault** [fiji/LocalThickness#5]
Hello,

Just to verify, does this plugin use voxel spacing info during the computation?

**Comment by ctrueden** [comment]
@soupault Briefly glancing through the source: it looks like [yes](https://github.com/fiji/LocalThickness/blob/LocalThickness_-4.0.2/src/main/java/sc/fiji/localThickness/LocalThicknessWrapper.java#L205-L228), but width only (not height), and only if you use the "Local Thickness (masked, calibrated, silent)" command.
